### ISSUE TITLE
Fixing ORDER BY ASC | DESC 

### ISSUE THREAD

**Issue by xD3f4L7x** [lorenzobrenin/open#1]
Per fixare l'ordinamento crescente/decrescente delle colonne (senza modificare troppo il resto del codice) basta che modifichi le 4 righe dei th in questa maniera:   (ti metto in allegato anche uno screen)

```
<tr>
      <th> <a href="es_Tab_list.php?order=model ASC">Model</a><span>  </span><a href="es_Tab_list.php?order=model DESC">v</a> </th>
      <th> <a href="es_Tab_list.php?order=brand ASC">Brand</a><span>  </span><a href="es_Tab_list.php?order=brand DESC">v</a> </th>
      <th> <a href="es_Tab_list.php?order=engine_size ASC">Engine Size</a><span>  </span><a href="es_Tab_list.php?order=engine_size DESC">v</a> </th>
      <!-- <th> <a href="es_Tab_list.php?order= ' DESC'"><button>DESC</button></a> </th> -->
</tr>
```

![Screenshot 2022-03-20 162701](https://user-images.githubusercontent.com/100155378/159169882-2d820447-2130-44b5-b0bf-86363b7af021.png)

**Comment by lorenzobrenin** [comment]
Grazie mille, gentilissimo. Non riuscivo proprio ad inquadrare come risolverlo
